command:
  - "python"
  - "-m"
  - "backend.main"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "01d40772d8293b41"
  - name: CARESIGNAL_FALLBACK_ON_ERROR
    value: "true"
  - name: CARESIGNAL_DATABRICKS_LIMIT
    value: "1000"
  - name: CARESIGNAL_PINCODE_LIMIT
    value: "25000"
